<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="38565" started-at="2017-01-30T06:06:21Z" finished-at="2017-01-30T06:07:00Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="38565" started-at="2017-01-30T06:06:21Z" finished-at="2017-01-30T06:07:00Z">
      <class name="com.testscripts.GmailLoginScript">
        <test-method status="PASS" signature="launch()[pri:0, instance:com.testscripts.GmailLoginScript@77cd7a0]" name="launch" is-config="true" duration-ms="15702" started-at="2017-01-30T11:36:21Z" finished-at="2017-01-30T11:36:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method status="PASS" signature="login()[pri:0, instance:com.testscripts.GmailLoginScript@77cd7a0]" name="login" duration-ms="10095" started-at="2017-01-30T11:36:37Z" finished-at="2017-01-30T11:36:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="launch()[pri:0, instance:com.testscripts.GmailLoginScript@77cd7a0]" name="launch" is-config="true" duration-ms="12700" started-at="2017-01-30T11:36:47Z" finished-at="2017-01-30T11:37:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method status="FAIL" signature="testFail()[pri:0, instance:com.testscripts.GmailLoginScript@77cd7a0]" name="testFail" duration-ms="7" started-at="2017-01-30T11:37:00Z" finished-at="2017-01-30T11:37:00Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at com.testscripts.GmailLoginScript.testFail(GmailLoginScript.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFail -->
      </class> <!-- com.testscripts.GmailLoginScript -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
